name: Bug 反馈
description: 反馈使用中遇到的问题
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        请仅反馈一个问题，多个问题请分别提交 issue。

  - type: checkboxes
    attributes:
      label: 提交前请确认
      options:
        - label: 已在仓库中搜索过，没有找到相同或类似的 issue
          required: true
        - label: 确认本次仅提交**一个**问题
          required: true

  - type: checkboxes
    id: platform
    attributes:
      label: 平台
      description: 请选择问题发生的平台（可多选）
      options:
        - label: Windows
        - label: macOS
    validations:
      required: true

  - type: input
    attributes:
      label: 系统型号和版本
      placeholder: "例：Windows 11 24H2 / macOS 15.3 (MacBook Air M2)"
    validations:
      required: false

  - type: input
    attributes:
      label: 软件版本
      placeholder: "例：1.0.4"
    validations:
      required: false

  - type: textarea
    attributes:
      label: 问题描述
      placeholder: 尽量详细地描述你遇到的问题
    validations:
      required: true
